### ISSUE TITLE
Release build config for WormSim geppetto

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#118]

**Comment by adrianq** [comment]
@tarelli from our conversation I understood you basically would like to override [this property](https://github.com/openworm/org.geppetto.frontend/blob/master/pom.xml#L17) when executing mvn install -P master for the wormsim.
It is as simple as executing:
mvn install -P master "-DcontextPath=ContextPathForWormsim"

cc @gidilli

Is this what you were looking for guys?

**Comment by tarelli** [comment]
@adrianq yes, thanks! Maybe I'd just rename it to OrgGeppettoContextPath since it's not WormSim specific per se

**Comment by gidili** [comment]
@tarelli how does this stuff @adrianq points to relate to the 'performance' build (minified js / resources / stuff)?

**Comment by tarelli** [comment]
@adrianq nevermind I thought it was a variable @gidili specifying that parameter will enable us to use the master profile which enables compressione retaining the context path "org.geppetto.frontend"

**Comment by adrianq** [comment]
See [this PR](https://github.com/openworm/org.geppetto.frontend/pull/334) for a better explanation.

**Comment by gidili** [comment]
@adrianq @tarelli thanks for this - working great!
