### ISSUE TITLE
Italicize "C. elegans"

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/org.wormsim.frontend#119]
This is a bit (or a lot) pedantic: the words "*Caenorhabditis elegans*" and the abbreviation "*C. elegans*", as uncommon terms from a foreign language (Latin), should always be italicized.  (See https://en.wikipedia.org/wiki/Caenorhabditis_elegans)

Currently the copy used in WormSim shown to the user does not italicize these words.

I tried doing a repo search for some of the copy but I couldn't easily find where it is stored.  If someone could point me to it I'd be happy to make a pull request.

**Comment by gidili** [comment]
@MichaelCurrie agreed! Thanks for creating the issue to help tracking it :+1:

**Comment by gidili** [comment]
@MichaelCurrie fixed here --> https://github.com/openworm/org.wormsim.frontend/commit/e737216ccaccf996389567e7e5d77465011ee296 :dancers:
