### ISSUE TITLE
Swap in c302 NeuroML with names of backers

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#121]

**Comment by gidili** [comment]
Hi @pgleeson - I can see we have the file [here](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/c302_A_Full.nml), I tried to swap it in but I am getting some errors. 

I am assuming it's because the latest c302 nml (the one we have on live as a sample) has somewhat evolved since this one with backer names was generated.

I remember you had a script, any chance you could re-run it nad point me to the updated file so I can drop it into WormSim?

That way we will be able to do something with the backer name (show it on cell selection somewhere).

P.S. just noticed the links on the README file with backer names are broken, will one of your scripts take care of that too? :)

**Comment by pgleeson** [comment]
@gidili I've fixed the links on https://github.com/openworm/CElegansNeuroML/tree/master/OpenWormBackers.

Where is the version you're using in the samples located?

**Comment by gidili** [comment]
@pgleeson thanks for that!

[Here's the c302 we are using in live](https://github.com/openworm/org.geppetto.core/blob/development/src/main/resources/projects/C302/c302_A.nml), for WormSim we need the same but with backer names and I remembered you were doing that via script, correct?

**Comment by pgleeson** [comment]
@gidili [that's](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/c302_A_Full.nml) the correct file to replace it with. What's the specific error you're getting? Have you replaced the [LEMS file](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/LEMS_c302_A_Full.xml) too?

**Comment by gidili** [comment]
@pgleeson argh no! This is the [LEMS file](https://github.com/openworm/org.geppetto.core/blob/development/src/main/resources/projects/C302/LEMS_c302_A.xml) that's used at the moment, I'll try swapping both. 

Will this slow things down as there's more stuff in it?

**Comment by pgleeson** [comment]
The main differences are additional comments on the parameters used to generate the file, and also lots of `<OutputColumn>` elements to save the data, which you don't need/use. 

You might be best just trying updating the file name in:

    <Include file="/c302_A.nml"/>

to c302_A_Full.nml, and `<Simulation id="sim_c302_A"... target="c302_A">` -> `<Simulation id="sim_c302_A_Full"... target="c302_A_Full">`

**Comment by gidili** [comment]
@pgleeson ok got it, it's working now, I had changed the include file name but not the attributes in the Simulation element! Thanks!
