### ISSUE TITLE
Sanitize SPH recordings data

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#122]
There are some blips in the activation signal data (should be a sinusoidal) from the Sibernetic recording:

<img width="997" alt="screenshot 2015-08-13 17 41 52" src="https://cloud.githubusercontent.com/assets/68134/9255698/ef1a5748-41e2-11e5-8b68-c62cc90f1caf.png">

**Comment by gidili** [comment]
@skhayrulin any idea how to fix this without re-running and re-recording? Your sweet python scripting skills could come in handy to doctor the activation signal files to have nice smooth sinusoidals. As you can see there's a slight shift in the last N steps, so just subtracting whatever the shift is might work? Is this something you have time to help with so I can re-generate new recordings? :wink:

**Comment by skhayrulin** [comment]
@gidili I have two posible solution first we can get smoth half of one sinusoidal period reflect it and replace wrong half with new. 
![fix1](https://cloud.githubusercontent.com/assets/1581992/9268053/a9ef9fe0-427b-11e5-93ed-98e73eea3e92.png)

Second we can aproximate missed value and put it insted wrong 
<img width="165" alt="fix2" src="https://cloud.githubusercontent.com/assets/1581992/9268062/c71b1fcc-427b-11e5-9655-42b49577a663.png">

We can experement with data. Could you please give me this data  or show where I can find it?

**Comment by gidili** [comment]
@skhayrulin second one sounds better to me so that we preserve the rest of the data... even if it's "just a sinusoidal" would be nice to keep the actual sibernetic values and also different muscle cells will have shifted sinusoidal so if we just fix the blips we don't have to worry about losing the phase.

The file we are using to generate the recordings is in [the recording repository](https://github.com/openworm/org.geppetto.recording/tree/master/org/geppetto/recording/creators/tests/wormsim_recordings), the only txt file in there called "muscle_signal_evo.txt".

Thanks for helping with this!

**Comment by tarelli** [comment]
Meeting with Sergey later in the week for this issue.

**Comment by skhayrulin** [comment]
Send new file with "I hope" correct data of muscle's signal evolution:) wait for a news from @gidili

**Comment by gidili** [comment]
@skhayrulin @tarelli improvements... :)

<img width="1128" alt="screenshot 2015-10-05 10 53 31" src="https://cloud.githubusercontent.com/assets/68134/10277728/d7629f7a-6b4f-11e5-9138-50f927d4e938.png">

<img width="1353" alt="screenshot 2015-10-05 10 54 25" src="https://cloud.githubusercontent.com/assets/68134/10277732/db96a6ae-6b4f-11e5-9bab-81c0e7b30baa.png">

**Comment by gidili** [comment]
@skhayrulin @tarelli success! I slightly modified the interval when generating the recording and bingo :)

<img width="895" alt="screenshot 2015-10-05 11 27 35" src="https://cloud.githubusercontent.com/assets/68134/10278451/5f6dde8e-6b55-11e5-8b21-87315244401d.png">

**Comment by gidili** [comment]
Fix here --> https://github.com/openworm/org.wormsim.frontend/commit/0e70c37d1b44790b16c5e43befff979f74603472

**Comment by skhayrulin** [comment]
@gidili you're simply the best :+1:

**Comment by gidili** [comment]
@skhayrulin you're mah man, thanks for the new activation signals!

Below a re-enactment of how we fixed this with the power of collaboration:
![business-people-working-together-istock_000017346252medium-1024x682](https://cloud.githubusercontent.com/assets/68134/10278561/319a9abe-6b56-11e5-8c6a-74b6e90e96db.jpg)

**Comment by tarelli** [comment]
@gidili @skhayrulin yeah, that's medicine, no rocks.
