### ISSUE TITLE
Indicate better how to get back to the nervous system

### ISSUE THREAD

**Issue by blawlor** [openworm/org.wormsim.frontend#126]
I had to use the browser back-button to go from the muscle simulation to the menu when I choose between muscle and nervous system. If this is correct, it might need explicit instructions: There are many options on the simulation menu and I spent a while looking for the button to return, when told to return by the guided tour.

**Comment by gidili** [comment]
@blawlor the idea is that you click the home button (logo on the top left) - we initially had another home bottom in top right... maybe worth revisiting!

**Comment by blawlor** [comment]
There are two home buttons but they seem to be there to reset the worm's
position and orientation respectively. Neither of them took me back to the
muscle/nervous system choice.

**Comment by gidili** [comment]
@blawlor oh really didn't think about that flow... you are correct in saying there is no way to go back to the nervous system from the muscles or the other way around, at the moment the only way is to click on the WormSim logo and go back to the main page and pick again.

**Comment by blawlor** [comment]
And that's just fine - but perhaps say that explicitly in the tour - i.e.
mention clicking the wormsim (though I think I tried that - are you sure
this works?)

**Comment by gidili** [comment]
@blawlor yeah it works (at least on my machine lol)... but you make a good point to mention it at the end of the tour. Also we can easily add a link to the other simulation at the end of the guided tour.

**Comment by gidili** [comment]
<img width="306" alt="screenshot 2015-08-14 18 26 41" src="https://cloud.githubusercontent.com/assets/68134/9279841/0e96f17e-42b2-11e5-84af-ad2168c7474b.png">

@blawlor better? :smiley:

**Comment by blawlor** [comment]
LGTM :-)

**Comment by gidili** [comment]
@blawlor :smile: :+1: 

I also played with the idea of linking from the guided tour text to the other simulation but I am conflicted about it since I am not sure it is beneficial to the flow to encourage users to go over there while they are still on this flow. Also 2 tabs with WebGL a-go-go on some less powerful systems might degrade the experience significantly...
