### ISSUE TITLE
Show backers names on cell selection on c302

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#127]
We have backer names in the file now - need to figure out how to fish them out as they are not showing on the json objects. MIght have to do with the fact that they are declared as population properties and they are being ignored by the model interpreter.

- [ ] fish out properties from .nml 
- [ ] respond to selection event and show the backer name

**Comment by gidili** [comment]
Backer names are defined as [properties of a NeuroML population](https://github.com/openworm/org.wormsim.frontend/blob/development/appdata/wormsim/models/c302_A.nml#L114).

Properties can be fished out from a population (in Java) with something like: 
```
Population p = new Population();
List<Property> prop = p.getProperty(); 
```

Need to understand where this should happen (NeuroML [model interpreter](https://github.com/openworm/org.geppetto.model.neuroml/blob/development/src/main/java/org/geppetto/model/neuroml/services/NeuroMLModelInterpreterService.java)?) so that the client receives those properties when the model is serialized.

cc: @pgleeson @adrianq @tarelli

**Comment by tarelli** [comment]
NeuroMLModelIntetpreter should be extended if they are not being fetched
yet.

**Comment by adrianq** [comment]
They are not being fetched yet. We need to extend the populate model tree functionality and once this is done you can access this information client side as it would be stored in the runtime tree model. The one thing is that you will have to call getModelTree(). 

I believe getProperty belongs to standalone component. This is a base component and most of the components extends from it. So it would be as simple as adding it [here](https://github.com/openworm/org.geppetto.model.neuroml/blob/12ff9749c9eb90fc07aa29ba35dd335880baa79d/src/main/java/org/geppetto/model/neuroml/utils/modeltree/PopulateNeuroMLModelTreeUtils.java#L1335). I have updated the neuromlmodel lib in the last release so there shouldn't be any problem.

**Comment by gidili** [comment]
I added the following as per @adrianq's suggestion at line of PopulateNeuroMLModelTreeUtils:
```
for (Property property : standaloneComponent.getProperty())
{
   standaloneChildren.add(PopulateNodesModelTreeUtils.createTextMetadataNode(property.getTag(), property.getTag(), new StringValue(property.getValue())));
}
```
But I can't seem figure out why this code doesn't seem to get him when I call getModelTree on entities.

**Comment by adrianq** [comment]
@gidili: hangout. Otherwise, it is going to take the whole week to solve this thing and we have a wedding to get drunk at! ;)
