### ISSUE TITLE
Simulation buttons should link to custom WormSim Geppetto frontend

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#32]
The custom WormSim frontend should have a WormSim logo, a home button and modified simulation controls.

@mlolson had this in place in his demos and the WormSim custom controls were in this repo: https://github.com/mlolson/wormsim-components 

We should create a org.wormsim.bower repo similar to https://github.com/openworm/org.geppetto.bower with those controls.

**Comment by jrmartin** [comment]
There's a new repository for the wormsim bower components. Live instance needs to be updated with this new bower json to see changes
