### ISSUE TITLE
Sprint 41 Review Card

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#35]
From sprint 41 review as discussed with @jrmartin and @tarelli at the review meeting:

- [x] improve scene illumination
- [x] fix neuronal collada export
- [x] add wormsim custom components source code to wormsim repo
- [x] css changes are not being shown in amazon instance, need to figure out 
- [x] There is a strange border around the 3D canvas, resizing screen should resize canvas so that there is no frame around it

Forgot anything?

**Comment by jrmartin** [comment]
@gidili I added one more, the css changes made are not being incorporated into the less files. Not sure what's going there,not familiar with less. I think this card will be more than 5 hour for next week, might have to split it

**Comment by gidili** [comment]
@jrmartin cheers, thanks for doing that, we'll split it if we have too!
