### ISSUE TITLE
Deploy WormSim to test amazon instance and document manual deployment

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#38]

**Comment by jrmartin** [comment]
File for manual deployment can be find in geppetto carpet under "Wormsim Deployment Commands", css less comments on docs.geppetto.org under development added too

**Comment by gidili** [comment]
@jrmartin awesome! Links to both? Having trouble tracking them down! :)

**Comment by jrmartin** [comment]
Here;s the doc with commands https://docs.google.com/a/metacell.us/document/d/11G89BpnZLu_3ibzn0EZU_wR5XD9rw0m0crg8I5rv5u8/edit

and the section describing CSS/LESS http://docs.geppetto.org/en/latest/styling.html
