### ISSUE TITLE
Swap buttons to show different layers of the worm with a 3 options slider on wormsim main page

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#40]
At the moment transition happen via button click, should be a slider with 3 positions. Also could use some performance improvement by preloading meshes as right now the transition is really slow.

**Comment by gidili** [comment]
Thinking to use this slider: http://refreshless.com/nouislider/

Would be nice to have a vertical slider with 3 positions: Cuticle + muscles + neurons / muscles + neurons / neurons only (basically remove layers as we go down).

Would be interesting to try and have a permanent tooltip (see slider [examples](http://refreshless.com/nouislider/examples/)) and we could re-use the [icons](https://github.com/openworm/openwormbrowser-ios/tree/master/ImageAssets) from the WormBrowser app.

@dariodippi do you think you can help with this one as we discussed? If so I'll assign to you.

**Comment by dariodippi** [comment]
@gidili  I will be happy to do it. 
As mentioned on skype, i will work on it in the weekend.

**Comment by gidili** [comment]
@dariodippi cool you're assigned! :+1:

**Comment by tarelli** [comment]
@dariodippi hey Dario, how's this going? :)

**Comment by gidili** [comment]
@tarelli we setup the dev env today with @dariodippi so now he's all set and ready to kick ass

**Comment by gidili** [comment]
@dariodippi @mihairaulea this card is now obsolete, we are keeping the buttons instead of swapping in the slider, as per mockup here --> https://github.com/openworm/org.wormsim.frontend/issues/47
