### ISSUE TITLE
Improve transition between 3D models on main page

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#44]
Need to improve performance and make it so when the different models are selected the transition is smooth.

**Comment by gidili** [comment]
I had a look at this - at the moment we are loading the 3 different models one at the time and wiping everything else every time. I was hoping there could be an easy way to preload the 3 of them so that the transition would be seamless, but from investigating a bit it seems to the only way to do that is to have all the models in one collada file (instead of 3) and hide and show based on groups. this probably involved tinkering with the blender model a bit so that the stuff is grouped the way we want it to be and then changing our js code to hide/show groups instead of wiping and reloading every time.

@tarelli @jrmartin any better ideas?

**Comment by tarelli** [comment]
@gidili why is the only way putting everything in the same file? Couldn't we load all of them and just change the opacity of the three meshes to display any combination we want?

**Comment by gidili** [comment]
@tarelli that's what I had in mind originally, but after reading a bit from my limited knowledge of three.js it seems like you can't load 3 different collada models at once, when you load it wiped what's already there.   Do you know of a way of loading 3 different collada models from 3 different files into the same canvas / scene?

**Comment by tarelli** [comment]
@gidili that's possible for sure (in the wiggling worm we'll be loading 96 of them :))

**Comment by gidili** [comment]
Fixed with this --> https://github.com/openworm/org.wormsim.frontend/commit/b551d4b454b2bca1d7f7879cd077bc6b3be44a5d
