### ISSUE TITLE
Map model entity names to recording entity names

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#46]
Muscle cells go from 0-95 based on the Sibernetic model. We need to map 0-95 to actual muscle cell names in C. elegans.

**Comment by gidili** [comment]
Hey @skhayrulin - I know the Sibernetic model is closely mapped to real anatomy, except for one extra muscle cell that was added that is not in the real worm. What's the best way of doing this mapping in your opinion and do you have time to help us out with this producing a spreadsheet with the mapping This is gonna be very useful for the wormsim so we can show real cell names when for example we plot activation signals.

**Comment by skhayrulin** [comment]
Sorry @gidili I haven't seen your message I'll think a bit and write you back soon :)

**Comment by gidili** [comment]
Thanks @skhayrulin - I was hoping @a-palyanov might already have a mapping somewhere from when he built the model, but if not your help in building the mapping would be highly appreciated! :)

**Comment by skhayrulin** [comment]
@gidili yes I think @a-palyanov has such information or somethink like this

**Comment by a-palyanov** [comment]
Giovanni, is it what you expected (in attachment)?

2015-04-21 15:03 GMT+06:00 Giovanni Idili <notifications@github.com>:

**Comment by gidili** [comment]
Hey @a-palyanov thanks but didn't get the attachment, I think because this is a github thread and it will not allow attachments.

**Comment by gidili** [comment]
For reference (picture from @a-palyanov ):
![sibernetic c elegans model muscle mapping](https://cloud.githubusercontent.com/assets/68134/7315737/31730540-ea68-11e4-9e94-bc8dc724461f.png)

**Comment by gidili** [comment]
@a-palyanov @skhayrulin could you guys review the following spreadsheet and see if you think I mapped it right?

https://docs.google.com/spreadsheets/d/1sN_P9UP_Xjwtz9rH23TyYRD-ZBNlP9HvASX2NQ37v8c/edit?usp=sharing

In particular @a-palyanov I think that your arrows on the picture from the VL quadrant should point to the arrays below (MVL lines instead of MVR, same as the red arrows on the VL quadrant). If that's not the case then I am misinterpreting something!

**Comment by a-palyanov** [comment]
Hi Giovanni,

Yes, you mapped the connections right in the shared spreadsheet.

>Arrows on the picture from the VL quadrant should point to the arrays
below (MVL lines instead of MVR, >same as the red arrows on the VL
quadrant). If that's not the case then I am misinterpreting something!
​You are right about this too - I've made a mistake in this drawing, and
noticed it only now, after your comment. It is only in the drawing - the
code and your muscle mapping in your spreadsheet are correct.

**Comment by gidili** [comment]
@a-palyanov great, thanks a lot for reviewing! :+1:
