### ISSUE TITLE
Style WormSim

### ISSUE THREAD

**Issue by tarelli** [openworm/org.wormsim.frontend#47]
- [x] Style landing page with sign up
- [x] Style create your worm page
- [x] Style look at your worm page
- [ ] Style forgot password page and confirmation page
- [x] Style Worm Settings page

**Comment by tarelli** [comment]
Look at your worm draft, later on I will work at the CSS level to double check detailed consistency across the different screens (background/flat vs non flat buttons, etc).
![mockupname](https://cloud.githubusercontent.com/assets/81127/7444930/b554b0ca-f193-11e4-8c5e-ab751ef30550.png)
Notes:
  * The buttons at the bottom are toggle, their style changes as they are clicked (pushed vs non pushed)
  * The background circle as the buttons are made in CSS3
  * The worm never comes out of the circle
  * As the user zooms in with the buttons the blue line on the left gets bigger to reflect the size of the worm (if zoom in doubles the size of the worm the line becomes twice as long)
  * The background can be found [here](https://dl.dropboxusercontent.com/u/7538688/Background.png)

**Comment by slarson** [comment]
@tarelli Some thoughts for when you get to styling the landing page.  

* The current mockup is sparse b/c it doesn't have any information.  
* We should at least add a sentence or some bullets for features that makes them want to run the video.
* We also considered a low friction approach for the page to show what wormsim is even before the video gets run, like the way Airbnb.com shows html5 video that conveys the basic idea of what the site is about.

**Comment by tarelli** [comment]
@slarson thanks, note airbnb switched away from the mpg video in the background, now they have just a carousel of images, maybe it was taking too long to load on low bandwidth

**Comment by tarelli** [comment]
@mihairaulea 
![landingpage](https://cloud.githubusercontent.com/assets/81127/7517851/582a9a1a-f4cf-11e4-9ac0-ccfd74e3a669.png)
- [ ] Clicking on the play button opens a video (use the kickstarter one for now)
![landingwithvideo](https://cloud.githubusercontent.com/assets/81127/7517855/5bde8b1c-f4cf-11e4-9a6e-1c9650254e16.png)
- [ ] Hovering on the play button changes its color to wormsim green
- [ ] Use bootstrap stylesheet for the page [link](http://getbootstrap.com/css/#grid-options)
- [ ] The design is responsive (that's why we want to use bootstrap) so the background and all the elements get adjusted as you resize 
The background  (it is slightly different to the previous one in the main, update that too) 
![backgroundnew](https://cloud.githubusercontent.com/assets/81127/7517936/d5842620-f4cf-11e4-922e-969a147a83be.png)
The Worm
![landingworm](https://cloud.githubusercontent.com/assets/81127/7517938/dafbf524-f4cf-11e4-822e-f6adae1dea59.png)

**Comment by gidili** [comment]
@tarelli very nice! As discussed if there's time left would be nice to have that worm moving in the background, but definitely not a priority.

**Comment by mihairaulea** [comment]
hello guys, i'm on it!

**Comment by gidili** [comment]
@tarelli since worm settings is going away, password is the only one left right?

**Comment by tarelli** [comment]
@gidili yes but that will be super simple, low priority for now Id say
