### ISSUE TITLE
Review WormSim

### ISSUE THREAD

**Issue by tarelli** [openworm/org.wormsim.frontend#48]
- [ ] Pressing enter doesn't let you login after typing username/password
- [ ] Color picker disappears under the page and you are obliged to scroll
- [ ] What's the point of the worm settings page? To change the name and the colour? Then why are we displaying the colour picker in the main page? Should it be removed? I wouldn't it make it so easy to change the name/colour as if those are things that the user would normally do, i.e. I'd remove both options from the main page.
- [ ] The reset password email needs to be updated

**Comment by gidili** [comment]
@tarelli we could remove the editable stuff and keep the worm settings page then, I think it's better so that it's not so easy to edit those fields.

**Comment by gidili** [comment]
This card is now obsolete, as the UI has been re-designed as per https://github.com/openworm/org.wormsim.frontend/issues/47
