### ISSUE TITLE
Customize worm flow review

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#50]
- [x] update the font
- [x] make font bigger
- [x] camera rotates around the worm
- [x] position the worm like mockups
- [x] make color picker options the same as mockup
- [x] change mesh color instead of light
- [x] change cursor to pointer on clickable items
- [x] hookup last arrow to go to the next page (button)
- [x] positioning of items closer to mockups

**Comment by mihairaulea** [comment]
Can't figure out the spotlight for the life of me... Help, please.

**Comment by gidili** [comment]
@mihairaulea I am assuming you have looked at this [as a reference](http://threejs.org/docs/#Reference/Lights/SpotLight), but this examples seems to have what we want: https://stemkoski.github.io/Three.js/Shadow.html

Maybe you can use that for inspiration :)

**Comment by tarelli** [comment]
@mihairaulea does [this](https://stemkoski.github.io/Three.js/Shadow.html) help?

**Comment by mihairaulea** [comment]
we need a powerful white light; that will alter the color of the cuticle after selection. i did have a look at that.

**Comment by mihairaulea** [comment]
also, rotating the camera around the worm is the same as rotating the worm and the light, but poses a lot more problems for the scaling and centering of the worm. please advise.

**Comment by tarelli** [comment]
```
SpotLight(hex, intensity, distance, angle, exponent)

hex — Numeric value of the RGB component of the color. 
intensity — Numeric value of the light's strength/intensity. 
```

**Comment by gidili** [comment]
@mihairaulea @tarelli I think we should close this one and open a new one just for the spotlight - so we can merge the PR for the rest of the stuff.

**Comment by gidili** [comment]
OK - spotlight issue captured here --> https://github.com/openworm/org.wormsim.frontend/issues/56

This is now in review.  @mihairaulea please open a pull request.
