### ISSUE TITLE
Wormsim frontend review card

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#62]
First pass looks great - here's the bits and pieces we need to close before we can call it ready for the beta release:

**Landing page**:

- [x] "request" and "login" to change color on hover
- [x] show video controls (youtube embed flag) so that if they want to go full screen they can

**Customize wormsim flow**: 

- [x] we should never have a login button on this page as the user can never see this page unless they are logged in
- [x] add logout button
- [x] implement some kind of color change on arrows on hover
- [x] on the color picker, the pointer should change to indicate it's a clickable element
- [x] on "give it a name" page, the textbox shouldbe empty and on focus with the cursor blinking with some some sample text like "type my name here"
- [x] make sure long names display correctly - I tried a longer one than "Spock" and it was being partially cut
- [x] on the final page it should grab the user name (we have a name hardcoded at the moment) and the name of the worm dynamically
- [x] change last arrow to some kind of save button to make it clear that's the end of the flow

**Main page**

- [x] add logout button
- [x] cuticle color should the same they picked during the customize flow
- [x] worm should never appear as coming out of the petri dish (try rotate after it's zoomed max to see this)
- [x] worm should never appear on top of the buttons (same as above) 
- [x] mouse pointer should be changed to clickable when hovering on buttons (skin, muscles, neurons)
- [x] worm should never disappear - simplify the logic so that the buttons are not independent toggles on/off but only one at the time can be selected 
   - skin - shows cuticle(the 3 meshes are loaded so it can be seen there's stuff inside)
   - muscles - muscles and neurons are shown
   - neurons - only nervous system is shown
- [x] adjust scale on petri dish, basically the number shouldn't change but as the worm gets bigger the 1mm bar gets bigger and bigger, when the worm is as long as the diameter of the dish then the bar should be as big as the diameter but it's still 1 mm  
- [x] the "new progress" button should be disabled, it's just meant as a "coming soon" hint (text will also change later)
- [x] the simulation buttons should link to the geppetto environment (links with relative paths can be copied from development branch)

**General**

- [x] when the user is logged in we need a logout button on the customize worm flow and on the main page
- [x] make sure to test flows where the user goes away and comes back, should behave as follows:
   - the first time the user logs in the customize worm flow is presented
   - if they complete the customize worm flow, this flow is never seen again for now (we can make name and color editable later on from settings as it used to be but for now we are getting rid of this) and the user once they login will fall onto the main page (the one with the dish)
   - if the user leaves before completing the customize worm flow, they'll start again from the start (no need to remember where they left it). We might decide to save the worm details (name and color) if they get there and press next and then re-populate if they come back after leaving without finishing the flow, but for now let's focus on the flow.

After all of this is done we will merge the newWormInfo branch into development. 

@tarelli @mihairaulea please take time to review and check if the above makes sense before we do the last pass

**Comment by gidili** [comment]
@mihairaulea will review later on today - I assume it's all committed in the same branch.

**Comment by mihairaulea** [comment]
@gidili i will do the submit request after i review it once more. will ping you.

**Comment by tarelli** [comment]
@gidili @mihairaulea the worm should be cutout by the circle like in this example http://threejs.org/examples/webgl_multiple_canvases_circle.html , we need to let the user zoom as much as they want (making a single neuron big for instance) but having the view limited by the circle
