### ISSUE TITLE
Scale bar adjustments

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#65]
- [ ] white scale bar length should be the same as the dish diameter and aligned with the dish

![screenshot 2015-05-28 15 23 28](https://cloud.githubusercontent.com/assets/68134/7862392/82a6986e-054d-11e5-971e-c42ceef62957.png)

- [ ] blue bar size increase when zooming but the number shouldn't change as the worm gets zoomed to a lenght similar to the blue bar size  (make sure the bar is roughly as long as the worm after zooming in and out etc)

**Comment by gidili** [comment]
@mihairaulea not sure if you lost this in a merge from the other branch

**Comment by mihairaulea** [comment]
@gidili ,i saw @tarelli commented on this, saying the petri dish should act like a mask. which one is it, guys?

**Comment by gidili** [comment]
@mihairaulea We are actually saying the same thing - regardless of how much they zoom the dish should act like a mask, the worm should never appear on top of the dish / buttons (as documented in this one --> https://github.com/openworm/org.wormsim.frontend/issues/66). 

To resolve the confusion in terms of the scale bar, once they are fully zoomed, the bar is full and all blue. If they zoom more - we might decide to let them do that if it looks nicer so that they can see more details - it still will stay full (all blue) at that point.

**Comment by mihairaulea** [comment]
"If they zoom more - we might decide to let them do that if it looks nicer so that they can see more details - it still will stay full (all blue) at that point." Please give me clear instructions, as i want to close things here.

**Comment by tarelli** [comment]
@mihairaulea Hey Mihai, they are able to zoom more, the bar will be all blue at that point, it will go back to being only a portion of the full bar once they zoom out enough for the worm to fit again the dish, sorry about the confusion on this.

**Comment by gidili** [comment]
@mihairaulea this is fixed - it now grows and goes back to the original size.
