### ISSUE TITLE
Zoom worm bugs

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#66]
- [x] worm still ends up on top of buttons (try zooming out and zooming back in etc till it happens - **the canvas has to cut off in a circle as we might decide to let users zoom more to see smaller details**

![screenshot 2015-05-28 14 35 51](https://cloud.githubusercontent.com/assets/68134/7862255/a4d2c6b6-054c-11e5-90b6-56bbf10923d5.png)

- [x] sometimes the zoom doesn't work (login with tester@test.com / password to see this)

![screenshot 2015-05-28 15 10 47](https://cloud.githubusercontent.com/assets/68134/7862275/b8094a52-054c-11e5-8bb5-529a46c714b1.png)

![screenshot 2015-05-28 15 18 24](https://cloud.githubusercontent.com/assets/68134/7862288/d4c2a56c-054c-11e5-95c7-bdec9d6d3818.png)

**Comment by gidili** [comment]
@mihairaulea reviewed - looking good! Thanks :+1: 

![screenshot 2015-06-01 15 24 32](https://cloud.githubusercontent.com/assets/68134/7914992/80b1c060-0872-11e5-98d5-9b17d51bed4f.png)

**Comment by pgleeson** [comment]
Nice! Can those somas be made spherical though @gidili?

**Comment by gidili** [comment]
@pgleeson yes of course, we can just throw in the nicer collada (as long as it's not too big)!

**Comment by tarelli** [comment]
@gidili @pgleeson That collada is a direct export in Blender of what's in the Virtual Worm, the somas are not spheres there but more complex meshes, adding more polygons is possible is general but the model would become quite heavier I'm afraid, we could try though.

**Comment by pgleeson** [comment]
@tarelli @gidili it would be good to get a bit more detail on the somas, though the rest of the cylinders for the dendrites and axons could still have a reduced number of polygons.
