### ISSUE TITLE
Zooming all the way in/out a couple of times results in a worm increasingly bigger

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#68]
![screenshot 2015-06-02 15 25 12](https://cloud.githubusercontent.com/assets/68134/7944534/275bf6f6-0963-11e5-8d95-c9785c6b1e7e.png)

**Comment by tarelli** [comment]
@gidili at what point does the worm get bigger? 1+ 1-? 2+ 2-?

**Comment by gidili** [comment]
@tarelli if you zoom in 3 times, and then you zoom out 3 times, it's slightly bigger than when you started. If you do it again, it gets bigger again. And so on.

**Comment by tarelli** [comment]
@gidili  if you do only one cycle does it keep the original size?

**Comment by gidili** [comment]
@tarelli even if I do 1 zoom-in / 1 zoom-out every time, if I do it enough times you can see it's very slowly growing (slower than if you zoom N times in / N times out)

**Comment by tarelli** [comment]
@gidili @mihairaulea what code are we using to zoom in/zoom out?

**Comment by MichaelCurrie** [comment]
This isn't helpful at all but I'll note that NormalizedWormPlottable had exactly the same problem which I fixed two days ago.  Totally different systems so I'm sure the solution is not going to be the same.  [My solution](https://github.com/openworm/movement_validation/commit/f4b208841146e98b769ea3ddefcbd2114fd605a6) was:

'''
            # We must reset this or else repetitive expanding and contracting
            # of the window will cause the view to zoom in on the subplots
            self.set_axes_extents()
'''

**Comment by gidili** [comment]
@tarelli this code here, .incrementZoomEnd same as in Geppetto connected to the + / - zoom buttons: https://github.com/openworm/org.wormsim.frontend/blob/newWormflow/src/main/webapp/js/worm-zoom.js#L156

@MichaelCurrie thanks! I am sure it's something similar! :)

**Comment by tarelli** [comment]
@gidili a bit of a hack but what if during zoom out we slightly increase the factor? It probably is an underlying bug of the trackball controls we are using.

**Comment by gidili** [comment]
@tarelli I'll give it a shot but I don't understand why this does not happen in Geppetto for example

**Comment by gidili** [comment]
Closed with this commit --> https://github.com/openworm/org.wormsim.frontend/commit/7037997dbdc94c8d4805161823e24ae3f1093ee8

For the time being I tweaked the zooming parameters so that zooming in X times and then zooming out the same amount of times leaves the scene as it was.
