### ISSUE TITLE
Add footer with copyright / link to OpenWorm and whatnot

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#79]

**Comment by borismarin** [comment]
COPYRIGHT????????

**Comment by gidili** [comment]
@borismarin Y U NO LIKE OpenWorm copyright like in everything else.

**Comment by borismarin** [comment]
COPYRIGHT????

**Comment by slarson** [comment]
Footer is there but creates havoc in mobile mode & overlaps with text on the page -- needs fixing.
