### ISSUE TITLE
Fix cross-browser glitches (firefox and chrome to behave and look the same)

### ISSUE THREAD

**Issue by gidili** [openworm/org.wormsim.frontend#80]
Noticed some weird stuff in firefox compare to chrome:

- [ ] logo on petri dish page looks cropped on firefox (should look same as chrome)
- [ ] make sure intro tutorial flow on petri dish page is the same (buttons are not showing up, probably some js glitch erroring and messing things up)

**Comment by slarson** [comment]
@gidili Can you look and see what the weird stuff is?  Not seeing it ATM.

**Comment by gidili** [comment]
@slarson not on landing page, but saw a broken logo on firefox on the petri dish page + tutorial functionality not working as expected in firefox (the simulation buttons were not showing) probably due to some javascript glitch
