### ISSUE TITLE
Question mark with info popover next to request invite

### ISSUE THREAD

**Issue by slarson** [openworm/org.wormsim.frontend#84]
Site should answer the obvious question people will have as to why access is not completely open.  Otherwise we'll get the question repeatedly (and probably will anyway).

If we do a little question mark with popup info, this may at least dispel some questions.

**Comment by gidili** [comment]
@slarson an FAQ html page would probably be a nice to have, including explanation for that

**Comment by slarson** [comment]
Popover implemented.  Still left to do: 

- [ ] update color of link
- [ ] add better text to the popover
