### ISSUE TITLE
Welcome email in response to registration

### ISSUE THREAD

**Issue by slarson** [openworm/org.wormsim.frontend#86]
Someone who signs up should be receive an email confirmation.  That email confirmation should contain social share links to leverage network effects

**Comment by slarson** [comment]
Need to confirm stormpath is actually logging the email addresses correctly...

**Comment by gidili** [comment]
@slarson it is logging them correctly, just click on accounts under the landing page directory and the accounts will show:
![screenshot 2015-06-26 10 05 58](https://cloud.githubusercontent.com/assets/68134/8374203/7c381192-1beb-11e5-9892-46f61600528f.png)

**Comment by slarson** [comment]
First pass welcome & verification emails created.  Need to add additional share links for Facebook, G+

**Comment by slarson** [comment]
Trying to fix this now but stormpath is having a partial outage :-/
